config/routes.rb
Score::Application.routes.draw do
  resources :catalogs do
    resources :items
  end

  resources :activities do
    resources :participations
    member do
      get 'scoreboard'
      get 'review'
      post 'submit_review'
    end
  end

  root :to => 'activities#index'

end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :activity
  has_many :grades
  attr_accessible :attachment_url, :description, :display_name
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
  before_filter :find_activity

  # GET /participations
  # GET /participations.json
  def index
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { render json: @activity.participations }
    end
  end

  # GET /participations/1
  # GET /participations/1.json
  def show
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { render json: Participation.find(params[:id]) }
    end
  end

  # GET /participations/new
  # GET /participations/new.json
  def new
    @participation = Participation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @participation }
    end
  end

  # GET /participations/1/edit
  def edit
    @participation = Participation.find(params[:id])
  end

  # POST /participations
  # POST /participations.json
  def create
    @participation = Participation.new(params[:participation])
    @participation.user = current_user
    @participation.activity = @activity

    respond_to do |format|
      if @participation.save
        format.html { redirect_to activities_url, notice: 'Participation was successfully created.' }
        format.json { render json: @participation, status: :created, location: @participation }
      else
        format.html { render action: "new" }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /participations/1
  # PUT /participations/1.json
  def update
    @participation = Participation.find(params[:id])
    @participation.user = current_user
    @participation.activity = @activity

    respond_to do |format|
      if @participation.update_attributes(params[:participation])
        format.html { redirect_to activities_url, notice: 'Participation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @participation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /participations/1
  # DELETE /participations/1.json
  def destroy
    @participation = Participation.find(params[:id])
    @participation.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Participation was successfully removed.' }
      format.json { head :no_content }
    end
  end

protected
  def find_activity
    @activity = Activity.find(params[:activity_id])
  end
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/participations/_form.html.erb
<%= form_for [@activity, @participation], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :display_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :display_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :attachment_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :attachment_url, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= yield :more_actions %>
    <%= link_to 'Back to Activities', activities_path, :class => 'btn'  %>
  </div>
<% end %>

app/views/participations/edit.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<% content_for :more_actions do %>
  <%= link_to 'Quit This Activity',
              activity_participation_path(@activity),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
<% end %>

<%= render :partial => 'form' %>

app/views/participations/index.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:activity_id) %></th>
      <th><%= model_class.human_attribute_name(:display_name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:attachment_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @participations.each do |participation| %>
      <tr>
        <td><%= link_to participation.id, participation_path(participation) %></td>
        <td><%= participation.user_id %></td>
        <td><%= participation.activity_id %></td>
        <td><%= participation.display_name %></td>
        <td><%= participation.description %></td>
        <td><%= participation.attachment_url %></td>
        <td><%=l participation.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_participation_path(participation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      participation_path(participation),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_participation_path,
            :class => 'btn btn-primary' %>

app/views/participations/new.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1>Participate Activity: <%= @activity %> </h1>
</div>
<%= render :partial => 'form' %>

app/views/participations/show.html.erb
<%- model_class = Participation -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @participation.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:activity_id) %>:</strong></dt>
  <dd><%= @participation.activity_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:display_name) %>:</strong></dt>
  <dd><%= @participation.display_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @participation.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:attachment_url) %>:</strong></dt>
  <dd><%= @participation.attachment_url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              participations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_participation_path(@participation), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              participation_path(@participation),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>