config/routes.rb
Score::Application.routes.draw do
  resources :catalogs do
    resources :items
  end

  resources :activities do
    resources :participations
    member do
      get 'scoreboard'
      get 'review'
      post 'submit_review'
    end
  end

  root :to => 'activities#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :catalog
  has_many :grades
  attr_accessible :description, :max_limit, :min_limit, :title, :priority

  def options
    (min_limit..max_limit).to_a
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :find_catalog

  def index
    respond_to do |format|
      format.html { redirect_to @catalog }
      format.json { render json: @catalog.items }
    end
  end

  def show
    respond_to do |format|
      format.html { redirect_to @catalog }
      format.json { render json: Item.find(params[:id]) }
    end
  end

  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(params[:item])
    @item.catalog = @catalog

    respond_to do |format|
      if @item.save
        format.html { redirect_to @catalog, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @item = Item.find(params[:id])
    @item.catalog = @catalog

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @catalog, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to @catalog, notice: 'Item was successfully removed.' }
      format.json { head :no_content }
    end
  end

protected
  def find_catalog
    @catalog = Catalog.find(params[:catalog_id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for [@catalog, @item], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :min_limit, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :min_limit, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :max_limit, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :max_limit, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :priority, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :priority, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                catalog_items_path(@catalog), :class => 'btn' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:catalog_id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:min_limit) %></th>
      <th><%= model_class.human_attribute_name(:max_limit) %></th>
      <th><%= model_class.human_attribute_name(:priority) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.id, catalog_item_path(@catalog, item) %></td>
        <td><%= link_to item.catalog, catalog_path(item.catalog) %></td>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.min_limit %></td>
        <td><%= item.max_limit %></td>
        <td><%= item.priority %></td>
        <td><%=l item.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_catalog_item_path(@catalog, item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      catalog_item_path(@catalog, item),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_catalog_item_path,
            :class => 'btn btn-primary' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:catalog_id) %>:</strong></dt>
  <dd><%= @item.catalog_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @item.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @item.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:min_limit) %>:</strong></dt>
  <dd><%= @item.min_limit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:max_limit) %>:</strong></dt>
  <dd><%= @item.max_limit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:priority) %>:</strong></dt>
  <dd><%= @item.priority %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              catalog_items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_catalog_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              catalog_item_path(@item),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>