config/routes.rb
Score::Application.routes.draw do
  resources :catalogs do
    resources :items
  end

  resources :activities do
    resources :participations
    member do
      get 'scoreboard'
      get 'review'
      post 'submit_review'
    end
  end

  root :to => 'activities#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :catalog
  has_many :participations
  has_many :grades, through: :participations
  attr_accessible :is_public, :title, :catalog_id

  def to_s
    title
  end

  def reviewers
    grades.collect(&:user_id).uniq
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_filter :find_activity, except: [:index, :new, :create]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    respond_to do |format|
      format.html
      format.json { render json: @activity }
    end
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(params[:activity])
    @activity.user = current_user
    @activity.catalog = Catalog.find(params[:activity][:catalog_id])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activities_url, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity.user = current_user

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to activities_url, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully removed.' }
      format.json { head :no_content }
    end
  end

  def review
    respond_to do |format|
      format.html
      format.json { head :no_content }
    end
  end

  def submit_review
    Grade.transaction do
      @activity.participations.each do |part|
        Grade.delete_all(user_id: current_user.id, participation_id: part.id)
        @activity.catalog.items.each do |item|
          name = "p#{part.id}i#{item.id}"
          grade = Grade.new
          grade.user = current_user
          grade.participation = part
          grade.item = item
          grade.score = params[name]
          grade.save
        end
      end
    end

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Your review was successfully updated.' }
      format.json { head :no_content }
    end
  end

  def scoreboard
  end

protected
  def find_activity
    @activity = Activity.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for @activity, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :catalog_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :catalog_id, Catalog.all, :id, :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :is_public, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :is_public, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= yield :more_actions %>
    <%= link_to 'Back to Activities', activities_path, :class => 'btn' %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/activities/index.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th>#Participants</th>
      <th></th>
      <th>#Reviewers</th>
      <th></th>
      <th><%= model_class.human_attribute_name(:catalog_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td>
          <% if activity.is_public or @current_user.is_owner_of(activity) %>
            <%= link_to activity.title, scoreboard_activity_path(activity) %>
          <% else %>
            <%= activity.title %>
          <% end %>
        </td>
        <td><%= activity.participations.count %></td>
        <td>
          <% if part = @current_user.participated_in(activity) %>
            <%= link_to 'Edit Participation',
                        edit_activity_participation_path(activity, part),
                        class: 'btn btn-mini' %>
          <% else %>
            <%= link_to 'Participate',
                        new_activity_participation_path(activity),
                        class: 'btn btn-mini btn-success' %>
          <% end %>
        </td>
        <td><%= activity.reviewers.count %></td>
        <td>
          <%= link_to 'Review',
                      review_activity_path(activity),
                      class: 'btn btn-mini btn-primary' %>
        </td>
        <td><%= link_to activity.catalog, activity.catalog %></td>
        <td><%=l activity.created_at, format: '%Y-%m-%d %H:%M:%S %Z' %></td>
        <td>
          <% if @current_user.is_owner_of(activity) %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_activity_path(activity), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        activity_path(activity),
                        :method => :delete,
                        :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                        :class => 'btn btn-mini btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Activity',
            new_activity_path,
            :class => 'btn btn-primary' %>

app/views/activities/new.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/activities/review.html.erb
<div class="page-header">
  <h1>Review: <%= @activity %></h1>
</div>

<%= form_tag submit_review_activity_path(@activity) do %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>姓名</th>
      <th>描述</th>
      <% @activity.catalog.items.each do |item| %>
        <th><%= item.title %></th>
      <% end %>
      <th>总分</th>
    </tr>
  </thead>
  <tbody>
    <% @activity.participations.each do |part| %>
      <tr>
        <td><%= part.display_name %></td>
        <td><%= part.description %></td>
        <% @activity.catalog.items.each do |item| %>
          <td>
            <%= select_tag "p#{part.id}i#{item.id}",
                            options_for_select(item.options, Grade.find_or_max(@current_user, part, item)),
                            class: [:span, :score], style: 'width: 50px',
                            min: item.min_limit, max: item.max_limit %>
          </td>
        <% end %>
        <td class="total"></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= submit_tag 'Submit Review', :class => 'btn btn-primary' %>
  <%= link_to 'Back to Activities', activities_path, :class => 'btn' %>
</div>

<% end %>

<% content_for :scripts do %>
<script type="text/javascript">
$(function() {
  compute_total = function() {
    sum_values_of = function(a) {
      var s = 0;
      a.each(function(i, e) {
        s += parseInt($(e).val());
      });
      return s;
    };

    $('.total').each(function(i, t) {
      $(t).text(sum_values_of($(t).parent().find('.score')));
    });
  };

  compute_total();
  $('.score').click(compute_total).blur(compute_total);
});
</script>
<% end %>

app/views/activities/show.html.erb
<%- model_class = Activity -%>
<div class="page-header">
  <h1>
    <%= @activity %>
    <%= link_to 'Participate', new_activity_participation_path(@activity), :class => 'btn btn-primary' %>
  </h1>
  <span>Creator: <%= @activity.user %></span>
  <span>Catalog: <%= link_to @activity.catalog, @activity.catalog %></span>
  <span>Public: <%= @activity.is_public %></span>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:display_name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:attachment_url) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @activity.participations.each do |participation| %>
      <tr>
        <td><%= participation.user_id %></td>
        <td><%= participation.display_name %></td>
        <td><%= participation.description %></td>
        <td><%= participation.attachment_url %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_activity_participation_path(@activity, participation), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      activity_participation_path(@activity, participation),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to 'Back to Activities', activities_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_activity_path(@activity), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              activity_path(@activity),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>