config/routes.rb
Score::Application.routes.draw do
  resources :catalogs do
    resources :items
  end

  resources :activities do
    resources :participations
    member do
      get 'scoreboard'
      get 'review'
      post 'submit_review'
    end
  end

  root :to => 'activities#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peer Review Board</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Peer Review Board", root_path, class: :brand %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Browse Activities", activities_path %></li>
          <li><%= link_to "Browse Catalogs", catalogs_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <% if notice = flash[:notice] %>
    <div class="alert fade in">
      <a class="close" data-dismiss="alert" href="#">&times;</a>
      <%= notice %>
    </div>
  <% end %>
  <div class="row">
    <div class="span12"><%= yield %></div>
  </div>
</div>
<%= yield :scripts %>
</body>
</html>